apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email-worker
  template:
    metadata:
      labels:
        app: email-worker
    spec:
      containers:
        - name: email-worker
          image: order-workers:latest
          imagePullPolicy: IfNotPresent
          workingDir: /app/workers
          command:
            - node
            - -r
            - ts-node/register
            - -r
            - tsconfig-paths/register
            - email.worker.ts
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
