apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: order-processing-system-api:latest
          imagePullPolicy: IfNotPresent
          workingDir: /app/api
          command:
            - npx
            - prisma
            - migrate
            - deploy
            - --schema=../prisma/schema.prisma
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
